1. **Array Creation**: Create a 1D NumPy array containing the numbers from 0 to 9. Then reshape it into a 2D array with 2 rows and 5 columns.

2. **Array Operations**: Given two NumPy arrays `a = np.array([1, 2, 3])` and `b = np.array([4, 5, 6])`, perform the following operations:
   - Add the two arrays.
   - Multiply the two arrays element-wise.
   - Find the dot product of the two arrays.


3. **Statistical Functions**: Create a NumPy array of 100 random numbers between 0 and 1. Calculate the mean, median, and standard deviation of the array.

4. **Boolean Indexing**: Create a NumPy array of integers from 1 to 20. Use boolean indexing to extract all even numbers from the array.

5. **Matrix Operations**: Create two 2D NumPy arrays (3x3) and perform matrix multiplication. Verify the result using the `np.dot()` function.


### pandas Problems

6. **DataFrame Creation**: Create a pandas DataFrame from a dictionary containing the following data:
   ```python
   data = {
       'Name': ['Alice', 'Bob', 'Charlie'],
       'Age': [25, 30, 35],
       'City': ['New York', 'Los Angeles', 'Chicago']
   }
   ```
   Display the DataFrame.


7. **DataFrame Indexing**: Using the DataFrame created in the previous problem, select the 'Name' and 'City' columns and display the result.

8. **Filtering Data**: Given the following DataFrame:
   ```python
   import pandas as pd

   data = {
       'Product': ['A', 'B', 'C', 'D'],
       'Price': [100, 150, 200, 250],
       'Stock': [30, 20, 0, 15]
   }
   df = pd.DataFrame(data)
   ```
   Filter the DataFrame to show only products that are in stock (Stock > 0).

9. **Group By**: Create a DataFrame with the following data:
   ```python
   data = {
       'Team': ['A', 'A', 'B', 'B', 'C', 'C'],
       'Points': [10, 20, 15, 25, 30, 10]
   }
   ```
   Group the DataFrame by 'Team' and calculate the total points for each team.

10. **CSV File Handling**: Write a pandas DataFrame to a CSV file named `students.csv` with the following data:
    ```python
    data = {
        'Student': ['John', 'Jane', 'Doe'],
        'Score': [85, 90, 78]
    }
    ```
    Then read the CSV file back into a DataFrame and display it.


In [1]:
# Q1
import numpy as np
a = np.arange(10)
print("Original array:")
print(a)
a = np.reshape(a, (2, 5))
print("Reshape 2D array:")
print(a)

Original array:
[0 1 2 3 4 5 6 7 8 9]
Reshape 2D array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
# Q2
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Original array:")
print(a)
print(b)
result = a + b
print("Addition of the two arrays:")
print(result)
result = a * b
print("Multiplication of the two arrays:")
print(result)
result = np.dot(a, b)
print("Dot product of the two arrays:")
print(result)

Original array:
[1 2 3]
[4 5 6]
Addition of the two arrays:
[5 7 9]
Multiplication of the two arrays:
[ 4 10 18]
Dot product of the two arrays:
32


In [4]:
# Q3
a = np.random.rand(100)
print("Original array:")
print(a)
mean = np.mean(a)
print("Mean:", mean)
median = np.median(a)
print("Median:", median)
std = np.std(a)
print("Standard Deviation:", std)

Original array:
[0.93382528 0.9727282  0.68909883 0.5583841  0.65229428 0.37512243
 0.97900757 0.64937875 0.58108161 0.36666113 0.64936642 0.03073597
 0.90554821 0.06903146 0.3950992  0.77564722 0.47775688 0.87837689
 0.25892941 0.62390509 0.04032899 0.70413097 0.90488326 0.31894745
 0.44123616 0.18295533 0.56365775 0.26419489 0.52249047 0.27380921
 0.03131525 0.63842938 0.27713993 0.50186737 0.50516296 0.66400401
 0.70862403 0.71223307 0.4185174  0.06494611 0.71002316 0.56550431
 0.39372674 0.9600923  0.29939573 0.66236185 0.8327485  0.07599675
 0.00567923 0.24226533 0.77304877 0.43047418 0.90445471 0.06027427
 0.76936956 0.77850102 0.62610999 0.59075273 0.62263751 0.57978459
 0.85538242 0.59594762 0.26485479 0.0086032  0.97260967 0.74343181
 0.37672667 0.77444531 0.56612153 0.78906206 0.39498916 0.56393764
 0.54990449 0.90575327 0.15808597 0.36015591 0.83542832 0.0598791
 0.97955181 0.05757588 0.67935631 0.85854614 0.57408449 0.89059091
 0.3294192  0.70957532 0.17705118 0.60853508 0.

In [5]:
# Q4
a = np.arange(1, 21)
print("Original array:")
print(a)
result = a[a % 2 == 0]
print("Extracted even numbers:")
print(result)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Extracted even numbers:
[ 2  4  6  8 10 12 14 16 18 20]


In [6]:
# Q5
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))
print("First array:")
print(a)
print("Second array:")
print(b)
result = np.matmul(a, b)
print("Matrix multiplication:")
print(result)
result = np.dot(a, b)
print("Matrix multiplication:")
print(result)

First array:
[[5 1 5]
 [5 6 3]
 [2 5 5]]
Second array:
[[4 3 8]
 [3 4 1]
 [1 6 3]]
Matrix multiplication:
[[28 49 56]
 [41 57 55]
 [28 56 36]]
Matrix multiplication:
[[28 49 56]
 [41 57 55]
 [28 56 36]]


In [7]:
# Q6
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [8]:
# Q7
print("Selecting Name and City columns:")
print(df[['Name', 'City']])

Selecting Name and City columns:
      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago


In [9]:
# Q8
data = {
    'Product': ['A', 'B', 'C', 'D'],
    'Price': [100, 150, 200, 250],
    'Stock': [30, 20, 0, 15]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
result = df[df['Stock'] > 0]
print("Products in stock:")
print(result)

Original DataFrame:
  Product  Price  Stock
0       A    100     30
1       B    150     20
2       C    200      0
3       D    250     15
Products in stock:
  Product  Price  Stock
0       A    100     30
1       B    150     20
3       D    250     15


In [10]:
# Q9
data = {
    'Team': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Points': [10, 20, 15, 25, 30, 10]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
result = df.groupby('Team').sum()
print("Total points by team:")
print(result)

Original DataFrame:
  Team  Points
0    A      10
1    A      20
2    B      15
3    B      25
4    C      30
5    C      10
Total points by team:
      Points
Team        
A         30
B         40
C         40


In [11]:
# Q10
data = {
    'Student': ['John', 'Jane', 'Doe'],
    'Score': [85, 90, 78]
}
df = pd.DataFrame(data)
df.to_csv('students.csv', index=False)
df = pd.read_csv('students.csv')
print("DataFrame from CSV:")
print(df)

DataFrame from CSV:
  Student  Score
0    John     85
1    Jane     90
2     Doe     78
